[settings]
lockfile = true
all_compile = false

[tools]
# NOTE: Python
python = "3.13"
uv = "0.11"
# NOTE: Formatter and linters
ruff = "0.15"
oxfmt = "0.43"
tombi = "0.9"
# NOTE: Utils
prek = "0.3"

[env]
_.python.venv = { create = true, path = ".venv" }
PYTHONPATH = "{{ config_root }}/src"
DJANGO_SETTINGS_MODULE = "nile_quran_community_api.settings"
DATABASE_URL = "sqlite:///{{ config_root }}/dev.sqlite"

[tasks.install]
description = "Install dependencies"
alias = "i"
run = ["mise install", "uv sync --all-groups --all-extras", "prek install"]

[tasks.migrate]
description = "Run database migrations"
alias = "m"
run = '''
django-admin makemigrations
django-admin migrate
django-admin setuproles
'''

[tasks.devserver]
description = "Run development server"
depends = ["migrate"]
alias = "dev"
run = '''
django-admin runserver
'''

[tasks.test]
description = "Run unit tests"
alias = "t"
run = "pytest"

[tasks.hooks]
description = "Run all pre-commit hooks"
alias = "h"
run = "prek run -a"
