[project]
name = "nile-quran-community-api"
description = "Nile Quran Community platform backend API"
requires-python = ">= 3.13"
license = "GPL-3.0-or-later"
classifiers = [
  "Framework :: Django",
  "Programming Language :: Python :: 3",
  "Programming Language :: Python :: 3.13",
]
dependencies = [
  "dj-database-url~=3.1",
  "django~=5.0",
  "django-cors-headers~=4.9",
  "django-filter~=25.2",
  "django-stubs~=5.2",
  "djangorestframework~=3.16",
  "djangorestframework-simplejwt~=5.5",
  "djangorestframework-stubs~=3.16",
  "drf-spectacular~=0.29",
  "psycopg2-binary~=2.9",
  "python-dotenv~=1.2",
  "uvicorn~=0.40",
  "whitenoise~=6.12",
]
dynamic = ["version"]

[project.scripts]
nqc = "nile_quran_community_api.cli.main:main"

[project.optional-dependencies]
tests = ["pytest", "pytest-django"]

[build-system]
requires = ["setuptools>=80", "setuptools-scm>=8"]
build-backend = "setuptools.build_meta"

[tool.mypy]
disable_error_code = ["import-untyped"]

[tool.pytest.ini_options]
python_files = ["test_*.py"]
pythonpath = ["src"]
testpaths = ["tests"]
DJANGO_SETTINGS_MODULE = "nile_quran_community_api.settings"

[tool.ruff.lint]
ignore = ["F403", "RUF012"]

[tool.setuptools]
include-package-data = true

[tool.setuptools_scm]
