# Generated by Django 6.1 on 2026-09-19 11:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("announcements", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="announcement",
            name="type",
            field=models.CharField(
                choices=[
                    ("general", "General"),
                    ("weekly_reflection", "Weekly Reflection"),
                    ("gathering", "Gathering"),
                    ("ilm_lesson", "Ilm Lesson"),
                    ("month_top_performers", "Month Top Performers"),
                ],
                max_length=32,
            ),
        ),
    ]
