# Generated by Django 6.1 on 2026-10-08 19:18

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("announcements", "0002_alter_announcement_type"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="announcement",
            name="reference_key",
            field=models.CharField(blank=True, db_index=True, max_length=64),
        ),
        migrations.AddConstraint(
            model_name="announcement",
            constraint=models.UniqueConstraint(
                condition=models.Q(("reference_key", ""), _negated=True),
                fields=("reference_key",),
                name="unique_announcement_reference_key",
            ),
        ),
    ]
