# Generated by Django 6.1 on 2026-10-09 13:16

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("announcements", "0003_announcement_reference_key_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="announcement",
            name="status",
        ),
    ]
