# Generated by Django 6.1 on 2026-10-10 07:46

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("announcements", "0005_rename_reference_key_announcement_idempotency_key"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="announcement",
            options={"ordering": ["-created_at"]},
        ),
        migrations.AlterModelOptions(
            name="announcementdelivery",
            options={"ordering": ["-created_at"]},
        ),
    ]
