# Generated by Django 6.1 on 2026-10-10 08:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("announcements", "0006_alter_announcement_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="announcement",
            name="content",
            field=models.TextField(max_length=4096),
        ),
    ]
