# Generated by Django 6.1 on 2026-09-11 13:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("goals", "0004_alter_goal_options"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="goal",
            name="scope",
        ),
        migrations.AddField(
            model_name="goal",
            name="end_date",
            field=models.DateField(default=None, null=True, verbose_name="end date"),
        ),
        migrations.AddField(
            model_name="goal",
            name="start_date",
            field=models.DateField(
                auto_now_add=True, null=True, verbose_name="start date"
            ),
        ),
    ]
