# Generated by Django 5.2.17 on 2026-09-11 14:13

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("goals", "0005_remove_goal_scope_goal_end_date_goal_start_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="goal",
            name="start_date",
            field=models.DateField(
                default=django.utils.timezone.localdate,
                null=True,
                verbose_name="start date",
            ),
        ),
    ]
