# Generated by Django 5.2.17 on 2026-09-11 15:01

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("goals", "0006_alter_goal_start_date"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="goal",
            options={
                "ordering": ["-id"],
                "verbose_name": "Goal",
                "verbose_name_plural": "Goals",
            },
        ),
    ]
