# Generated by Django 5.2.17 on 2026-08-16 05:04

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0007_alter_user_options_alter_user_email"),
    ]

    operations = [
        migrations.AddField(
            model_name="activity",
            name="multiplier",
            field=models.PositiveIntegerField(
                default=1,
                validators=[django.core.validators.MinValueValidator(1)],
                verbose_name="multiplier",
            ),
        ),
    ]
