# Generated by Django 5.2.17 on 2026-08-16 20:32

import django.contrib.auth.validators
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0008_activity_multiplier"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="first_name",
            field=models.CharField(
                blank=True,
                max_length=150,
                validators=[
                    django.core.validators.RegexValidator(
                        message="Only Arabic letters are allowed.",
                        regex="^[\u0600-ۿ\\s]+$",
                    )
                ],
                verbose_name="first name",
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="last_name",
            field=models.CharField(
                blank=True,
                max_length=150,
                validators=[
                    django.core.validators.RegexValidator(
                        message="Only Arabic letters are allowed.",
                        regex="^[\u0600-ۿ\\s]+$",
                    )
                ],
                verbose_name="last name",
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="username",
            field=models.CharField(
                error_messages={"unique": "A user with that username already exists."},
                help_text="Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.",
                max_length=150,
                unique=True,
                validators=[
                    django.contrib.auth.validators.ASCIIUsernameValidator(
                        message="Enter a valid username. This value may contain only unaccented lowercase a-z and uppercase A-Z letters, numbers, and @/./+/-/_ characters."
                    )
                ],
                verbose_name="username",
            ),
        ),
    ]
