# Generated by Django 6.1 on 2026-09-12 13:19

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0010_alter_category_6_name"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="user",
            options={
                "ordering": ["id"],
                "verbose_name": "user",
                "verbose_name_plural": "users",
            },
        ),
    ]
