# Generated by Django 6.1 on 2026-09-14 19:39

import django.db.models.functions.text
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
        ("users", "0011_alter_user_options"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="user",
            constraint=models.UniqueConstraint(
                django.db.models.functions.text.Lower("username"),
                name="unique_username_ci",
                violation_error_message="A user with that username already exists.",
            ),
        ),
    ]
