# Generated by Django 6.1 on 2026-09-19 12:56

import django.core.validators
import phonenumber_field.modelfields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0012_user_unique_username_ci"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="academic_status",
            field=models.CharField(
                blank=True,
                choices=[
                    ("undergraduate", "Undergraduate student"),
                    ("postgraduate", "Postgraduate student"),
                    ("other", "Other"),
                ],
                max_length=20,
                verbose_name="academic status",
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="academic_status_other",
            field=models.CharField(
                blank=True, max_length=100, verbose_name="academic status (other)"
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="academic_year",
            field=models.CharField(
                blank=True,
                choices=[
                    ("1", "First year"),
                    ("2", "Second year"),
                    ("3", "Third year"),
                    ("4", "Fourth year"),
                    ("5", "Fifth year"),
                    ("graduate", "Graduate"),
                ],
                max_length=10,
                verbose_name="academic year",
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="birth_date",
            field=models.DateField(blank=True, null=True, verbose_name="birth date"),
        ),
        migrations.AddField(
            model_name="user",
            name="faculty",
            field=models.CharField(
                blank=True,
                choices=[
                    ("engineering", "Engineering"),
                    ("computer_science", "Computer Science / AI"),
                    ("business", "Business Administration"),
                    ("biotechnology", "Biotechnology"),
                    ("other", "Other"),
                ],
                max_length=20,
                verbose_name="faculty",
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="faculty_other",
            field=models.CharField(
                blank=True, max_length=100, verbose_name="faculty (other)"
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="has_islamic_studies",
            field=models.BooleanField(
                blank=True, null=True, verbose_name="has prior Islamic studies"
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="hometown",
            field=models.CharField(blank=True, max_length=255, verbose_name="hometown"),
        ),
        migrations.AddField(
            model_name="user",
            name="islamic_studies_source",
            field=models.CharField(
                blank=True, max_length=255, verbose_name="Islamic studies source"
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="memorized_juz",
            field=models.PositiveSmallIntegerField(
                blank=True,
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(30),
                ],
                verbose_name="memorized Quran parts (juz)",
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="phone_number",
            field=phonenumber_field.modelfields.PhoneNumberField(
                blank=True,
                help_text="Include your country code.",
                max_length=128,
                region=None,
                verbose_name="phone number",
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="residence",
            field=models.CharField(
                blank=True, max_length=255, verbose_name="residence"
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="skills",
            field=models.TextField(blank=True, verbose_name="skills"),
        ),
        migrations.AddField(
            model_name="user",
            name="tajweed_level",
            field=models.CharField(
                blank=True,
                choices=[
                    ("beginner", "Beginner (no prior exposure to tajweed rules)"),
                    ("intermediate", "Intermediate (basic knowledge of tajweed rules)"),
                    ("proficient", "Proficient (skilled knowledge of tajweed rules)"),
                ],
                max_length=15,
                verbose_name="tajweed level",
            ),
        ),
    ]
