# Generated by Django 6.1 on 2026-10-09 17:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0013_user_discord_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="discord_id",
            field=models.CharField(
                blank=True,
                help_text="Discord account ID, used to mention the user in announcements.Found via Discord's Developer Mode (right click a user, Copy User ID).",
                max_length=32,
                verbose_name="discord ID",
            ),
        ),
    ]
